name: thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python & Tools
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel

  # Data Manipulation & Math
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.15.2

  # Visualization
  - matplotlib
  - seaborn=0.13.2

  # Machine Learning & Stats
  - scikit-learn=1.6.1
  - xgboost=3.1.3
  - statsmodels=0.14.2

  # EEG Specific (Neuroscience)
  - mne=1.10.1
  - autoreject=0.4.3
  - pyriemann=0.10  

  # Pip dependencies
  - pip:
    - mne-bids